In [1]:
# import modules
import torch

In [3]:
#pytorch is a library that deals with tensors again a tensor is a number,vector,matrix or n-dimentional array or a single number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

In [14]:
t2 = torch.tensor([1,2,3,4],requires_grad)
t3 = torch.tensor([[1,2],[3,4],[5,6],[2,3],dtype=float)

In [18]:
t4 = t2 * 2
t4

tensor([2, 4, 6, 8])

In [21]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)

In [22]:
Y = (w*x)+b
Y

tensor(17., grad_fn=<AddBackward0>)

In [23]:
Y.backward()

In [25]:
w.grad

tensor(3.)

In [30]:
# full function is used to fill the tensor with an element
a = torch.ones([1,3])
a
#

tensor([[1., 1., 1.]])

tensor([[1., 1., 1.]])